img_height: 96
img_width: 96
batch_size: 32
patience: 5
dataset_path: data/split_classified
datasets: # List of datasets to be used for training
  - name: takeover      # Name of the dataset (required)
    path: data/split_classified # Path to the dataset (required)
    transforms: # List of ordered transformations to be applied to the dataset, choose order and type based on your dataset and model
      - grayscale      
      - save_img : {n: 50, save_dir: "data/transforms_debug/datset"} # Save every nth image to the specified directory for debugging
      # ToTensor using torchvision.transforms.ToTensor
      # Converts a PIL Image or numpy.ndarray (H x W x C) in the range [0, 255] to a torch.FloatTensor of shape (C x H x W) in the range [0.0, 1.0]
      - ToTensor 

      # Normalization using torchvision.transforms.Normalize
      - normalize: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
            # mean (sequence) – Sequence of means for each channel.
            # std (sequence) – Sequence of standard deviations for each channel.
model_name: torch_custom
model_type: custom
num_workers: 16
output_path: results/torch_custom

# Transfer Learning configuration
transfer_learning_epochs: 40  # Epochs for transfer learning phase
transfer_learning_rate: 0.001  # Learning rate for transfer learning
transfer_weight_decay: 0.0001  # Weight decay for transfer learning

# Fine-tuning configuration
fine_tune: True
fine_tune_epochs: 20
fine_tuning_learning_rate: 0.00001
fine_tuning_weight_decay: 0.0001
num_unfreezed_feature_layers: 15  # Unfreeze last 50 feature layers


# Additional parameters
# requires_grad: False # Whether to require gradients for the model parameters (make them trainable) | Defaults to False
# check_corrupted_images: False # Whether to check for corrupted images in the dataset | Defaults to False
# pin_memory - True # Whether to pin memory during data loading | Defaults to True
# profile - False  # Whether to profile the training process (causing training to be interrupted after few steps) | Defaults to False | FOR DEBUGGING ONLY